/**
 * Analysis catalog — frontend-safe typed definitions mirroring the backend registry.
 * All IDs must match /v1/capabilities/analyses.
 */

export type AnalysisCategory =
  | "schema"
  | "transform"
  | "privacy"
  | "profiling"
  | "temporal"
  | "concentration"
  | "representation"
  | "recommender"
  | "classification"
  | "regression"
  | "explanation"
  | "comparison"
  | "compliance";

export type RuntimeCategory = "fast" | "medium" | "slow";
export type SensitivityLevel = "low" | "medium" | "high";

export interface AnalysisCatalogEntry {
  id: string;
  label: string;
  category: AnalysisCategory;
  description: string;
  requiredFormats: string[];
  compatibleFormats: string[];
  requiredFields: string[];
  requiresModel: boolean;
  requiresPredictions: boolean;
  requiresGroundTruth: boolean;
  requiresGroupField: boolean;
  requiresProbabilityOutput: boolean;
  backendRoute: string;
  producedArtifacts: string[];
  sensitivity: SensitivityLevel;
  runtime: RuntimeCategory;
  unavailableMessage: string;
}

const ALL_FORMATS = [
  "maskott_csv_v1", "becomino_json", "generic_xapi_json", "generic_xapi_jsonl",
  "generic_csv_tabular", "parquet_tabular",
];
const XAPI_FORMATS = ["maskott_csv_v1", "becomino_json", "generic_xapi_json", "generic_xapi_jsonl"];
const TABULAR_FORMATS = ["generic_csv_tabular", "parquet_tabular"];

export const ANALYSIS_CATALOG: AnalysisCatalogEntry[] = [
  { id: "schema_validation", label: "Schema Validation", category: "schema", description: "Validates the dataset against the named schema.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/datasets/validate", producedArtifacts: ["validation_report.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "xapi_compatibility_check", label: "xAPI Compatibility Check", category: "schema", description: "Scores dataset conformance to the xAPI specification.", requiredFormats: [], compatibleFormats: [...XAPI_FORMATS, ...TABULAR_FORMATS], requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/datasets/validate", producedArtifacts: ["xapi_compatibility_report.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "becomino_template_inference", label: "Becomino Template Inference", category: "schema", description: "Matches the dataset against known Becomino activity templates.", requiredFormats: ["becomino_json"], compatibleFormats: ["becomino_json"], requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/datasets/validate", producedArtifacts: ["becomino_template_match.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "Becomino template inference only applies to becomino_json format." },
  { id: "maskott_csv_to_xapi_transform", label: "Maskott CSV → xAPI Transform", category: "transform", description: "Transforms Maskott/Tactileo CSV into canonical xAPI JSONL.", requiredFormats: ["maskott_csv_v1"], compatibleFormats: ["maskott_csv_v1"], requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/datasets/{dataset_id}/transform", producedArtifacts: ["transformed.jsonl", "transform_report.json"], sensitivity: "low", runtime: "medium", unavailableMessage: "xAPI transform only applies to maskott_csv_v1 format." },
  { id: "pii_scan", label: "PII Field Scan", category: "privacy", description: "Detects columns containing personally identifiable information.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/audits/run (stage: pii_scan)", producedArtifacts: ["pii_report.json"], sensitivity: "high", runtime: "medium", unavailableMessage: "" },
  { id: "pseudonymisation_benchmark", label: "Pseudonymisation Benchmark", category: "privacy", description: "Applies HMAC pseudonymisation and benchmarks linkage risk reduction.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/audits/run (stage: pseudonymisation_benchmark)", producedArtifacts: ["pseudonymisation_report.json"], sensitivity: "high", runtime: "medium", unavailableMessage: "" },
  { id: "privacy_risk_profile", label: "Privacy Risk Profile", category: "privacy", description: "Computes a composite privacy risk score.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/audits/run (stage: privacy_risk_profile)", producedArtifacts: ["privacy_report.json"], sensitivity: "high", runtime: "medium", unavailableMessage: "" },
  { id: "missingness_profile", label: "Missingness Profile", category: "profiling", description: "Computes per-field missing value rates.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/audits/run (stage: profiling)", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "completeness_profile", label: "Completeness Profile", category: "profiling", description: "Reports fraction of rows with all required fields populated.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "type_profile", label: "Field Type Profile", category: "profiling", description: "Infers and reports the data type of each field.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "entropy_profile", label: "Entropy Profile", category: "profiling", description: "Computes Shannon entropy per categorical field.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "temporal_density_profile", label: "Temporal Density Profile", category: "temporal", description: "Analyses event distribution over time.", requiredFormats: [], compatibleFormats: [...XAPI_FORMATS, ...TABULAR_FORMATS], requiredFields: ["timestamp_field"], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/audits/run (stage: temporal_profile)", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "medium", unavailableMessage: "Temporal density profile requires a timestamp field." },
  { id: "session_density_profile", label: "Session Density Profile", category: "temporal", description: "Measures event density within sessions.", requiredFormats: [], compatibleFormats: [...XAPI_FORMATS, ...TABULAR_FORMATS], requiredFields: ["session_field", "timestamp_field"], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "medium", unavailableMessage: "Session density profile requires session and timestamp fields." },
  { id: "event_frequency_profile", label: "Event Frequency Profile", category: "temporal", description: "Counts total events per entity and item.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["entity_field"], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "verb_distribution", label: "Verb / ViewContext Distribution", category: "profiling", description: "Reports frequency distribution of activity verbs.", requiredFormats: [], compatibleFormats: XAPI_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "resource_type_distribution", label: "Resource Type Distribution", category: "profiling", description: "Reports proportion of interactions by resource type.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["item_field"], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "long_tail_profile", label: "Long-Tail Resource Profile", category: "concentration", description: "Identifies the fraction of resources responsible for most interactions.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["item_field"], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "metrics.concentration.long_tail", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "sparsity_analysis", label: "Interaction Matrix Sparsity", category: "concentration", description: "Computes sparsity of the user-item interaction matrix.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["entity_field", "item_field"], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "entity_dominance", label: "Entity Dominance Analysis", category: "concentration", description: "Identifies entities producing a disproportionate share of events.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["entity_field"], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "resource_dominance", label: "Resource Dominance Analysis", category: "concentration", description: "Identifies resources receiving a disproportionate share of interactions.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["item_field"], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "gini_concentration", label: "Gini Concentration", category: "concentration", description: "Measures inequality in event/resource contribution using the Gini coefficient.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["entity_field"], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "metrics.concentration.gini", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "coverage_at_k", label: "Coverage@K", category: "representation", description: "Estimates how broadly resources appear across top-K interaction lists.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["entity_field", "item_field"], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "metrics.coverage.coverage_at_k", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "representation_index", label: "Representation Index", category: "representation", description: "Composite score capturing how evenly content is distributed.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["entity_field", "item_field"], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "cooccurrence_summary", label: "Co-occurrence Summary", category: "representation", description: "Computes verb-object or resource co-occurrence patterns.", requiredFormats: [], compatibleFormats: XAPI_FORMATS, requiredFields: ["entity_field", "item_field"], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "medium", unavailableMessage: "" },
  { id: "recommender_precision_at_k", label: "Recommender Precision@K", category: "recommender", description: "Fraction of top-K recommendations matching ground truth.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["entity_field", "item_field"], requiresModel: false, requiresPredictions: true, requiresGroundTruth: true, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "medium", unavailableMessage: "Requires ranked predictions and ground-truth interactions." },
  { id: "recommender_recall_at_k", label: "Recommender Recall@K", category: "recommender", description: "Fraction of ground-truth items recovered in top-K.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["entity_field", "item_field"], requiresModel: false, requiresPredictions: true, requiresGroundTruth: true, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "medium", unavailableMessage: "Requires ranked predictions and ground-truth interactions." },
  { id: "recommender_hit_rate_at_k", label: "Recommender Hit Rate@K", category: "recommender", description: "Proportion of users with at least one top-K match.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["entity_field", "item_field"], requiresModel: false, requiresPredictions: true, requiresGroundTruth: true, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "medium", unavailableMessage: "Requires ranked recommendations and ground-truth interactions." },
  { id: "recommender_ndcg_at_k", label: "Recommender nDCG@K", category: "recommender", description: "Normalised Discounted Cumulative Gain at K.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["entity_field", "item_field"], requiresModel: false, requiresPredictions: true, requiresGroundTruth: true, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "medium", unavailableMessage: "nDCG@K requires a ranked recommendation list and ground-truth interaction set." },
  { id: "recommender_diversity", label: "Recommender Diversity", category: "recommender", description: "Intra-list diversity of recommendation outputs.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["entity_field", "item_field"], requiresModel: false, requiresPredictions: true, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "medium", unavailableMessage: "Requires recommendation predictions." },
  { id: "recommender_novelty", label: "Recommender Novelty", category: "recommender", description: "How surprising recommendations are relative to historical popularity.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["entity_field", "item_field"], requiresModel: false, requiresPredictions: true, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "medium", unavailableMessage: "Requires recommendation predictions." },
  { id: "classification_performance", label: "Classification Performance", category: "classification", description: "Accuracy, precision, recall, F1, and confusion matrix.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: ["target_field", "prediction_field"], requiresModel: false, requiresPredictions: true, requiresGroundTruth: true, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "Requires target and prediction class label fields." },
  { id: "regression_performance", label: "Regression Performance", category: "regression", description: "RMSE, MAE, R², residual statistics.", requiredFormats: [], compatibleFormats: TABULAR_FORMATS, requiredFields: ["target_field", "prediction_field"], requiresModel: false, requiresPredictions: true, requiresGroundTruth: true, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "Requires numeric target and prediction fields." },
  { id: "segment_performance", label: "Segment-Level Performance", category: "classification", description: "Performance metrics broken down by segment.", requiredFormats: [], compatibleFormats: TABULAR_FORMATS, requiredFields: ["target_field", "prediction_field", "group_field"], requiresModel: false, requiresPredictions: true, requiresGroundTruth: true, requiresGroupField: true, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "Requires target, prediction, and group fields." },
  { id: "fairness_by_group", label: "Fairness by Group", category: "classification", description: "Demographic parity, equalised odds, and predictive parity.", requiredFormats: [], compatibleFormats: TABULAR_FORMATS, requiredFields: ["target_field", "prediction_field", "group_field"], requiresModel: false, requiresPredictions: true, requiresGroundTruth: true, requiresGroupField: true, requiresProbabilityOutput: false, backendRoute: "metrics.fairness.fairness_by_group", producedArtifacts: ["metrics.json"], sensitivity: "high", runtime: "fast", unavailableMessage: "Fairness-by-group is unavailable because no group/segment field was selected." },
  { id: "model_feature_importance", label: "Global Feature Importance", category: "explanation", description: "SHAP or permutation-based global feature importance.", requiredFormats: [], compatibleFormats: TABULAR_FORMATS, requiredFields: [], requiresModel: true, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/models/{model_id}/explain", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "slow", unavailableMessage: "Model explanations are unavailable because no compatible model artifact or endpoint was supplied." },
  { id: "model_prediction_explanation", label: "Local Prediction Explanations", category: "explanation", description: "SHAP waterfall explanations for individual predictions.", requiredFormats: [], compatibleFormats: TABULAR_FORMATS, requiredFields: [], requiresModel: true, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/models/{model_id}/explain", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "slow", unavailableMessage: "Local explanations require a compatible model artifact." },
  { id: "model_partial_dependence", label: "Partial Dependence Plots", category: "explanation", description: "Marginal effect of features on model predictions.", requiredFormats: [], compatibleFormats: TABULAR_FORMATS, requiredFields: [], requiresModel: true, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "slow", unavailableMessage: "Partial dependence requires a compatible model adapter." },
  { id: "model_comparison", label: "Model Comparison", category: "comparison", description: "Side-by-side performance and explanation comparison of two models.", requiredFormats: [], compatibleFormats: TABULAR_FORMATS, requiredFields: [], requiresModel: true, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/models/compare", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "slow", unavailableMessage: "Model comparison requires two compatible model artifacts." },
  { id: "model_residual_diagnostics", label: "Residual Diagnostics", category: "regression", description: "Residual plots, heteroscedasticity, and outlier detection.", requiredFormats: [], compatibleFormats: TABULAR_FORMATS, requiredFields: ["target_field", "prediction_field"], requiresModel: false, requiresPredictions: true, requiresGroundTruth: true, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["metrics.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "Residual diagnostics require numeric target and prediction fields." },
  { id: "dataset_model_schema_check", label: "Dataset–Model Schema Check", category: "schema", description: "Validates dataset feature schema compatibility with the model.", requiredFormats: [], compatibleFormats: TABULAR_FORMATS, requiredFields: [], requiresModel: true, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["schema_compatibility_report.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "Schema check requires a registered model with a declared feature schema." },
  { id: "data_card_export", label: "Data Card Export", category: "compliance", description: "Structured dataset documentation card.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["data_card.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "model_card_export", label: "Model Card Export", category: "compliance", description: "Structured model documentation card.", requiredFormats: [], compatibleFormats: TABULAR_FORMATS, requiredFields: [], requiresModel: true, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["model_card.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "Model card export requires a registered model." },
  { id: "jsonld_compliance_graph", label: "JSON-LD Compliance Graph", category: "compliance", description: "Machine-readable audit evidence graph aligned with EU AI Act Annex IV.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/compliance/jsonld", producedArtifacts: ["compliance_graph.jsonld"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "sop_export", label: "SOP Export", category: "compliance", description: "Human-readable Standard Operating Procedure document.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["SOP.md", "SOP.html"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "audit_manifest_export", label: "Audit Manifest Export", category: "compliance", description: "Signed manifest of all audit inputs, parameters, and artifact hashes.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "", producedArtifacts: ["audit_manifest.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "carisma_metadata_export", label: "CARiSMA Metadata Export", category: "compliance", description: "Audit metadata in CARiSMA interoperability format.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/interoperability/carisma", producedArtifacts: ["carisma_metadata.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "lola_metadata_export", label: "LOLA Metadata Export", category: "compliance", description: "Dataset metadata in LOLA format.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/interoperability/lola", producedArtifacts: ["lola_metadata.json"], sensitivity: "low", runtime: "fast", unavailableMessage: "" },
  { id: "pdc_metadata_export", label: "PDC Metadata Export", category: "compliance", description: "Consent and policy metadata to the Personal Data Cooperative.", requiredFormats: [], compatibleFormats: ALL_FORMATS, requiredFields: [], requiresModel: false, requiresPredictions: false, requiresGroundTruth: false, requiresGroupField: false, requiresProbabilityOutput: false, backendRoute: "POST /v1/pdc/policy", producedArtifacts: ["pdc_metadata.json"], sensitivity: "high", runtime: "fast", unavailableMessage: "" },
];

export const ANALYSIS_BY_ID = Object.fromEntries(ANALYSIS_CATALOG.map((a) => [a.id, a]));

export function getAnalysisById(id: string): AnalysisCatalogEntry | undefined {
  return ANALYSIS_BY_ID[id];
}

export function getAnalysesForFormat(formatId: string): AnalysisCatalogEntry[] {
  return ANALYSIS_CATALOG.filter(
    (a) => a.compatibleFormats.length === 0 || a.compatibleFormats.includes(formatId)
  );
}
